ALTER TYPE "RepoFrequency" ADD VALUE IF NOT EXISTS 'EVERY_1_HOUR';
ALTER TYPE "RepoFrequency" ADD VALUE IF NOT EXISTS 'EVERY_2_HOURS';
ALTER TYPE "RepoFrequency" ADD VALUE IF NOT EXISTS 'EVERY_4_HOURS';
ALTER TYPE "RepoFrequency" ADD VALUE IF NOT EXISTS 'EVERY_6_HOURS';
